// <auto-generated>
// Rewired Constants
// This list was generated on 1/30/2026 9:00:19 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MoveHorizontal = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Forward")]
        public const int MoveForward = 6;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 7;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 8;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack")]
        public const int Attack = 9;
        
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisX")]
        public const int MenuAxisX = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisY")]
        public const int MenuAxisY = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAxisScroll")]
        public const int MenuAxisScroll = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuAccept")]
        public const int MenuAccept = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuBack")]
        public const int MenuBack = 4;
        
    }
}
