// <auto-generated>
// Rewired Constants
// This list was generated on 9/10/2025 3:32:11 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts
{
  public static partial class Action
  {
    // Default
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
    public const int Interact = 13;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Open Player Menu")]
    public const int OpenPlayerMenu = 19;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pause")]
    public const int Pause = 27;

    // Submarine
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Throttle")]
    public const int Throttle = 0;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Rudder")]
    public const int Rudder = 1;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Depth")]
    public const int Depth = 2;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Toggle Light")]
    public const int ToggleLight = 8;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Toggle Aim")]
    public const int ToggleAim = 10;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Fire Weapon")]
    public const int FireWeapon = 9;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Cycle Weapon")]
    public const int CycleWeapon = 12;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Ability")]
    public const int Ability = 11;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "Boost")]
    public const int Boost = 22;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Submarine", friendlyName = "SelectTarget")]
    public const int SelectTarget = 28;

    // Camera
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Camera", friendlyName = "Camera X")]
    public const int CameraX = 3;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Camera", friendlyName = "Camera Y")]
    public const int CameraY = 4;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Camera", friendlyName = "Camera Z")]
    public const int CameraZ = 5;

    // Menu
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Axis X")]
    public const int MenuAxisX = 14;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Axis Y")]
    public const int MenuAxisY = 15;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Axis Scroll")]
    public const int MenuAxisScroll = 18;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Accept")]
    public const int MenuAccept = 16;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Back")]
    public const int MenuBack = 17;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Next Tab")]
    public const int MenuTabNext = 20;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Menu Previous Tab")]
    public const int MenuTabPrev = 21;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "MenuDelete")]
    public const int MenuDelete = 26;

    // Map
    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Map", friendlyName = "Map Scroll X")]
    public const int MapScrollX = 23;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Map", friendlyName = "Map Scroll Y")]
    public const int MapScrollY = 24;

    [Rewired.Dev.ActionIdFieldInfo(categoryName = "Map", friendlyName = "Map Zoom")]
    public const int MapZoom = 25;

  }
}
